/**
 * `ares export`: decoded frames back out to interchange formats. The container was write-only
 * before this; every other tool in a pipeline needs a way back.
 *   mesh  → .obj (positions, UVs, normals, faces) or binary .ply
 *   splat → .spz / 3DGS .ply / .glb (KHR_gaussian_splatting) / .splat — see the importers
 */
import { dequantScale, type Aabb, type DecodedGeometry } from "@ares/core";
import type { EncodeMeshFrame } from "./geometry-encode.js";

/** Dequantize a decoded mesh block back to floats (positions, UVs, normals). */
export function decodedMeshToFrame(d: DecodedGeometry, box: Aabb, quantBitsPos: number, normalEncoding: number): EncodeMeshFrame {
  const s = dequantScale(quantBitsPos);
  const sx = (box.max[0] - box.min[0]) * s, sy = (box.max[1] - box.min[1]) * s, sz = (box.max[2] - box.min[2]) * s;
  const n = d.vertexCount;
  const positions = new Float32Array(n * 3);
  for (let i = 0; i < n; i++) {
    positions[i * 3] = box.min[0] + d.positionsQ[i * 4]! * sx;
    positions[i * 3 + 1] = box.min[1] + d.positionsQ[i * 4 + 1]! * sy;
    positions[i * 3 + 2] = box.min[2] + d.positionsQ[i * 4 + 2]! * sz;
  }
  let uvs: Float32Array | undefined;
  if (d.uvsQ) { uvs = new Float32Array(n * 2); for (let i = 0; i < n * 2; i++) uvs[i] = d.uvsQ[i]! / 65535; }
  let normals: Float32Array | undefined;
  if (d.normalsQ) {
    normals = new Float32Array(n * 3);
    if (normalEncoding === 1) {
      const q = new Int16Array(d.normalsQ.buffer, d.normalsQ.byteOffset, n * 2);
      for (let i = 0; i < n; i++) {
        let ox = q[i * 2]! / 32767, oy = q[i * 2 + 1]! / 32767;
        let oz = 1 - Math.abs(ox) - Math.abs(oy);
        if (oz < 0) { const tx = (1 - Math.abs(oy)) * (ox >= 0 ? 1 : -1), ty = (1 - Math.abs(ox)) * (oy >= 0 ? 1 : -1); ox = tx; oy = ty; }
        const l = Math.hypot(ox, oy, oz) || 1;
        normals[i * 3] = ox / l; normals[i * 3 + 1] = oy / l; normals[i * 3 + 2] = oz / l;
      }
    } else {
      for (let i = 0; i < n; i++) { normals[i * 3] = d.normalsQ[i * 4]! / 127; normals[i * 3 + 1] = d.normalsQ[i * 4 + 1]! / 127; normals[i * 3 + 2] = d.normalsQ[i * 4 + 2]! / 127; }
    }
  }
  return { positions, uvs, normals, indices: d.indices };
}

/** Wavefront OBJ text (1-based indices; v/vt/vn present as available). */
export function writeObj(f: EncodeMeshFrame, name = "ares"): string {
  const n = f.positions.length / 3;
  const parts: string[] = [`# exported by ares\no ${name}\n`];
  const p = f.positions;
  for (let i = 0; i < n; i++) parts.push(`v ${p[i * 3]} ${p[i * 3 + 1]} ${p[i * 3 + 2]}\n`);
  if (f.uvs) for (let i = 0; i < n; i++) parts.push(`vt ${f.uvs[i * 2]} ${f.uvs[i * 2 + 1]}\n`);
  if (f.normals) for (let i = 0; i < n; i++) parts.push(`vn ${f.normals[i * 3]} ${f.normals[i * 3 + 1]} ${f.normals[i * 3 + 2]}\n`);
  const idx = f.indices;
  const fmt = (i: number) => { const k = i + 1; return f.uvs && f.normals ? `${k}/${k}/${k}` : f.uvs ? `${k}/${k}` : f.normals ? `${k}//${k}` : `${k}`; };
  for (let t = 0; t < idx.length; t += 3) parts.push(`f ${fmt(idx[t]!)} ${fmt(idx[t + 1]!)} ${fmt(idx[t + 2]!)}\n`);
  return parts.join("");
}

/** Binary little-endian PLY with x y z [nx ny nz] [s t] and triangle faces. */
export function writeMeshPly(f: EncodeMeshFrame): Uint8Array {
  const n = f.positions.length / 3;
  const props = ["x", "y", "z", ...(f.normals ? ["nx", "ny", "nz"] : []), ...(f.uvs ? ["s", "t"] : [])];
  const tris = f.indices.length / 3;
  const header = `ply\nformat binary_little_endian 1.0\ncomment generated by ares-encoder\nelement vertex ${n}\n${props.map((p) => `property float ${p}`).join("\n")}\nelement face ${tris}\nproperty list uchar uint vertex_indices\nend_header\n`;
  const hb = new TextEncoder().encode(header);
  const vstride = props.length * 4;
  const out = new Uint8Array(hb.length + n * vstride + tris * 13);
  out.set(hb, 0);
  const dv = new DataView(out.buffer);
  let o = hb.length;
  for (let i = 0; i < n; i++) {
    dv.setFloat32(o, f.positions[i * 3]!, true); dv.setFloat32(o + 4, f.positions[i * 3 + 1]!, true); dv.setFloat32(o + 8, f.positions[i * 3 + 2]!, true); o += 12;
    if (f.normals) { dv.setFloat32(o, f.normals[i * 3]!, true); dv.setFloat32(o + 4, f.normals[i * 3 + 1]!, true); dv.setFloat32(o + 8, f.normals[i * 3 + 2]!, true); o += 12; }
    if (f.uvs) { dv.setFloat32(o, f.uvs[i * 2]!, true); dv.setFloat32(o + 4, f.uvs[i * 2 + 1]!, true); o += 8; }
  }
  for (let t = 0; t < tris; t++) {
    out[o] = 3; dv.setUint32(o + 1, f.indices[t * 3]!, true); dv.setUint32(o + 5, f.indices[t * 3 + 1]!, true); dv.setUint32(o + 9, f.indices[t * 3 + 2]!, true); o += 13;
  }
  return out;
}
