// ARES Explorer command handler — puts "Convert to .ares" in the Windows 11 SHORT context menu.
//
// Why a COM DLL at all: the registry verbs under HKCU\Software\Classes (tools/shell-integration.mjs)
// only reach the classic menu, the one behind "Show more options". The short Win11 menu is built
// exclusively from packaged IExplorerCommand handlers, so this is the only way in.
//
// Deliberately dependency-free: plain COM against shobjidl_core.h, no WIL, no C++/WinRT, no ATL.
// It builds with nothing but cl.exe and the Windows SDK, which is what a machine that has ever
// installed VS Build Tools already has, and it keeps the whole thing a single translation unit.
//
// What it does on Invoke: resolves the clicked item to a filesystem path and launches
//     wscript.exe "<repo>\ARES.vbs" app --open "<path>"
// which is the same entry point the classic verb and the Settings card use. The repo root is
// derived from THIS DLL's own location (<repo>\tools\msix\AresShell.dll -> up two), so the
// package never has to be told where it was installed.

#include <windows.h>
#include <shobjidl_core.h>
#include <shlwapi.h>
#include <strsafe.h>
#include <new>

// Generated by tools/msix/build.mjs: ARES_ROOT is the checkout this package was built from.
// The package is self-contained (see AppxManifest.xml), so this DLL runs from WindowsApps and
// cannot find the repo by walking up from its own path.
#include "AresRoot.h"

#pragma comment(lib, "shlwapi.lib")
#pragma comment(lib, "ole32.lib")
#pragma comment(lib, "shell32.lib")

// Keep in step with AppxManifest.xml and tools/msix/build.mjs.
// {7107EFE2-8605-4F5D-8757-7472171D3327}
static const CLSID CLSID_AresConvertCommand =
    { 0x7107efe2, 0x8605, 0x4f5d, { 0x87, 0x57, 0x74, 0x72, 0x17, 0x1d, 0x33, 0x27 } };

static LONG g_refModule = 0;
static HMODULE g_module = nullptr;

static void ModuleAddRef() { InterlockedIncrement(&g_refModule); }
static void ModuleRelease() { InterlockedDecrement(&g_refModule); }

static bool LauncherPath(wchar_t* out, size_t cch)
{
    return SUCCEEDED(StringCchPrintfW(out, cch, L"%s\\ARES.vbs", ARES_ROOT));
}

class AresConvertCommand : public IExplorerCommand
{
public:
    AresConvertCommand() : m_ref(1) { ModuleAddRef(); }

    // --- IUnknown -----------------------------------------------------------------------------
    IFACEMETHODIMP QueryInterface(REFIID riid, void** ppv) override
    {
        if (!ppv) return E_POINTER;
        if (riid == IID_IUnknown || riid == IID_IExplorerCommand) {
            *ppv = static_cast<IExplorerCommand*>(this);
            AddRef();
            return S_OK;
        }
        *ppv = nullptr;
        return E_NOINTERFACE;
    }
    IFACEMETHODIMP_(ULONG) AddRef() override { return InterlockedIncrement(&m_ref); }
    IFACEMETHODIMP_(ULONG) Release() override
    {
        LONG n = InterlockedDecrement(&m_ref);
        if (n == 0) { ModuleRelease(); delete this; }
        return n;
    }

    // --- IExplorerCommand ---------------------------------------------------------------------
    IFACEMETHODIMP GetTitle(IShellItemArray* items, LPWSTR* name) override
    {
        // A folder is a capture (frames on disk); a file is a single asset. Say which, because
        // the two do different things when the app opens them.
        const wchar_t* title = IsFolder(items) ? L"Convert folder to .ares" : L"Convert to .ares";
        return SHStrDupW(title, name);
    }

    IFACEMETHODIMP GetIcon(IShellItemArray*, LPWSTR* icon) override
    {
        // The icon ships inside the package, beside this DLL.
        wchar_t self[MAX_PATH];
        if (!GetModuleFileNameW(g_module, self, ARRAYSIZE(self))) { *icon = nullptr; return E_NOTIMPL; }
        wchar_t* slash = wcsrchr(self, L'\\');
        if (!slash) { *icon = nullptr; return E_NOTIMPL; }
        *slash = L'\0';
        wchar_t path[MAX_PATH];
        if (FAILED(StringCchPrintfW(path, ARRAYSIZE(path), L"%s\\Assets\\menu.ico", self))) { *icon = nullptr; return E_NOTIMPL; }
        if (!PathFileExistsW(path)) { *icon = nullptr; return E_NOTIMPL; }   // no icon is fine
        return SHStrDupW(path, icon);
    }

    IFACEMETHODIMP GetToolTip(IShellItemArray*, LPWSTR* tip) override { *tip = nullptr; return E_NOTIMPL; }

    IFACEMETHODIMP GetCanonicalName(GUID* guid) override { *guid = CLSID_AresConvertCommand; return S_OK; }

    IFACEMETHODIMP GetState(IShellItemArray* items, BOOL, EXPCMDSTATE* state) override
    {
        // Only offer the verb for something with a real filesystem path — the launcher takes a
        // path, so a virtual item (a library, This PC, a search result) has nothing to hand it.
        *state = HasFileSystemPath(items) ? ECS_ENABLED : ECS_HIDDEN;
        return S_OK;
    }

    IFACEMETHODIMP GetFlags(EXPCMDFLAGS* flags) override { *flags = ECF_DEFAULT; return S_OK; }

    IFACEMETHODIMP EnumSubCommands(IEnumExplorerCommand** e) override { *e = nullptr; return E_NOTIMPL; }

    IFACEMETHODIMP Invoke(IShellItemArray* items, IBindCtx*) override
    {
        if (!items) return E_INVALIDARG;
        IShellItem* item = nullptr;
        if (FAILED(items->GetItemAt(0, &item)) || !item) return E_FAIL;

        PWSTR target = nullptr;
        HRESULT hr = item->GetDisplayName(SIGDN_FILESYSPATH, &target);
        item->Release();
        if (FAILED(hr) || !target) return hr;

        wchar_t vbs[MAX_PATH];
        if (!LauncherPath(vbs, ARRAYSIZE(vbs))) { CoTaskMemFree(target); return E_FAIL; }

        // wscript.exe keeps it windowless. ARES.vbs -> tools\launch.ps1 -> ARES.mjs --open,
        // which starts or reuses the dev server and opens the Convert tab on this path.
        wchar_t args[2 * MAX_PATH + 64];
        hr = StringCchPrintfW(args, ARRAYSIZE(args), L"\"%s\" app --open \"%s\"", vbs, target);
        CoTaskMemFree(target);
        if (FAILED(hr)) return hr;

        SHELLEXECUTEINFOW ei = { sizeof(ei) };
        ei.fMask = SEE_MASK_NOASYNC | SEE_MASK_FLAG_NO_UI;
        ei.lpVerb = L"open";
        ei.lpFile = L"wscript.exe";
        ei.lpParameters = args;
        ei.nShow = SW_HIDE;
        return ShellExecuteExW(&ei) ? S_OK : HRESULT_FROM_WIN32(GetLastError());
    }

private:
    static bool HasFileSystemPath(IShellItemArray* items)
    {
        if (!items) return false;
        DWORD count = 0;
        if (FAILED(items->GetCount(&count)) || count == 0) return false;
        IShellItem* item = nullptr;
        if (FAILED(items->GetItemAt(0, &item)) || !item) return false;
        SFGAOF attrs = 0;
        bool ok = SUCCEEDED(item->GetAttributes(SFGAO_FILESYSTEM, &attrs)) && (attrs & SFGAO_FILESYSTEM);
        item->Release();
        return ok;
    }

    static bool IsFolder(IShellItemArray* items)
    {
        if (!items) return false;
        IShellItem* item = nullptr;
        if (FAILED(items->GetItemAt(0, &item)) || !item) return false;
        SFGAOF attrs = 0;
        bool folder = SUCCEEDED(item->GetAttributes(SFGAO_FOLDER, &attrs)) && (attrs & SFGAO_FOLDER);
        item->Release();
        return folder;
    }

    LONG m_ref;
};

class ClassFactory : public IClassFactory
{
public:
    ClassFactory() : m_ref(1) { ModuleAddRef(); }

    IFACEMETHODIMP QueryInterface(REFIID riid, void** ppv) override
    {
        if (!ppv) return E_POINTER;
        if (riid == IID_IUnknown || riid == IID_IClassFactory) {
            *ppv = static_cast<IClassFactory*>(this);
            AddRef();
            return S_OK;
        }
        *ppv = nullptr;
        return E_NOINTERFACE;
    }
    IFACEMETHODIMP_(ULONG) AddRef() override { return InterlockedIncrement(&m_ref); }
    IFACEMETHODIMP_(ULONG) Release() override
    {
        LONG n = InterlockedDecrement(&m_ref);
        if (n == 0) { ModuleRelease(); delete this; }
        return n;
    }

    IFACEMETHODIMP CreateInstance(IUnknown* outer, REFIID riid, void** ppv) override
    {
        if (outer) return CLASS_E_NOAGGREGATION;
        AresConvertCommand* cmd = new (std::nothrow) AresConvertCommand();
        if (!cmd) return E_OUTOFMEMORY;
        HRESULT hr = cmd->QueryInterface(riid, ppv);
        cmd->Release();
        return hr;
    }

    IFACEMETHODIMP LockServer(BOOL lock) override
    {
        if (lock) ModuleAddRef(); else ModuleRelease();
        return S_OK;
    }

private:
    LONG m_ref;
};

// --- DLL exports ------------------------------------------------------------------------------

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, void** ppv)
{
    if (!ppv) return E_POINTER;
    *ppv = nullptr;
    if (rclsid != CLSID_AresConvertCommand) return CLASS_E_CLASSNOTAVAILABLE;
    ClassFactory* f = new (std::nothrow) ClassFactory();
    if (!f) return E_OUTOFMEMORY;
    HRESULT hr = f->QueryInterface(riid, ppv);
    f->Release();
    return hr;
}

STDAPI DllCanUnloadNow() { return g_refModule == 0 ? S_OK : S_FALSE; }

BOOL WINAPI DllMain(HINSTANCE inst, DWORD reason, LPVOID)
{
    if (reason == DLL_PROCESS_ATTACH) {
        g_module = inst;
        DisableThreadLibraryCalls(inst);
    }
    return TRUE;
}
